export type CategoryKey = 'compressors' | 'fundamentals' | 'maintenance' | 'components' | 'controls' | 'airflow' | 'tools' | 'refrigerants' | 'safety'
export interface Article { slug: string; category: CategoryKey; title: string; summary: string; titleEs: string; summaryEs: string }

// 24 concise educational articles with EN and ES content.
export const articles: Article[] = [
  { slug: 'compressor-types', category: 'compressors', title: 'Types of Refrigeration Compressors', summary: 'Overview of hermetic, semi-hermetic, and scroll compressors, with typical applications and pros/cons.', titleEs: 'Tipos de compresores de refrigeración', summaryEs: 'Resumen de compresores herméticos, semiherméticos y scroll, con aplicaciones típicas y pros/contras.' },
  { slug: 'basic-cycle', category: 'fundamentals', title: 'The Basic Refrigeration Cycle', summary: 'Evaporation, compression, condensation, and expansion—how heat moves and why pressures matter.', titleEs: 'Ciclo básico de refrigeración', summaryEs: 'Evaporación, compresión, condensación y expansión: cómo se mueve el calor y por qué importan las presiones.' },
  { slug: 'preventive-ac', category: 'maintenance', title: 'Preventive Maintenance for Air Conditioners', summary: 'Filters, coils, electrical checks, and airflow—simple steps that extend equipment life and reduce energy use.', titleEs: 'Mantenimiento preventivo de aires acondicionados', summaryEs: 'Filtros, serpentines, revisiones eléctricas y flujo de aire: pasos simples que alargan la vida y reducen el consumo.' },
  { slug: 'filter-driers', category: 'components', title: 'Filter Driers', summary: 'Moisture and acid control protect the system. Learn where driers go and when to replace them.', titleEs: 'Secadores de filtro', summaryEs: 'Control de humedad y ácidos para proteger el sistema. Dónde instalar y cuándo reemplazar.' },
  { slug: 'thermostats', category: 'controls', title: 'Thermostats', summary: 'Mechanical vs. electronic thermostats, placement tips, and common troubleshooting points.', titleEs: 'Termostatos', summaryEs: 'Termostatos mecánicos y electrónicos, ubicación recomendada y fallas comunes.' },
  { slug: 'electronic-controls', category: 'controls', title: 'Electronic Controls', summary: 'Boards, sensors, and protection modules—why correct wiring and grounding are essential.', titleEs: 'Controles electrónicos', summaryEs: 'Placas, sensores y módulos de protección: importancia de cableado y puesta a tierra correctos.' },
  { slug: 'oils-lubes', category: 'maintenance', title: 'Oils and Lubricants', summary: 'Mineral, POE, and PAG oils: compatibility with refrigerants and good handling practices.', titleEs: 'Aceites y lubricantes', summaryEs: 'Aceites mineral, POE y PAG: compatibilidad con refrigerantes y buenas prácticas de manejo.' },
  { slug: 'motors-fans', category: 'airflow', title: 'Motors and Fans', summary: 'PSC vs. ECM motors, blade pitch, and keeping bearings lubricated for reliable airflow.', titleEs: 'Motores y ventiladores', summaryEs: 'Motores PSC vs. ECM, ángulo de palas y lubricación de rodamientos para un flujo confiable.' },
  { slug: 'expansion-valves', category: 'components', title: 'Expansion Valves', summary: 'TXVs and fixed orifices: superheat control, bulb placement, and contamination risks.', titleEs: 'Válvulas de expansión', summaryEs: 'TXV y orificios fijos: control de sobrecalentamiento, ubicación del bulbo y riesgos por contaminación.' },
  { slug: 'tools-accessories', category: 'tools', title: 'Tools and Technical Accessories', summary: 'Manifolds, vacuum pumps, scales, and recovery machines—basic kit for safe service.', titleEs: 'Herramientas y accesorios técnicos', summaryEs: 'Manómetros, bombas de vacío, balanzas y recuperadoras: kit básico para un servicio seguro.' },
  { slug: 'refrigerants-r134a', category: 'refrigerants', title: 'Refrigerant R-134a', summary: 'Common in domestic refrigeration; moderate pressures; check retrofit guidelines and regulations.', titleEs: 'Refrigerante R-134a', summaryEs: 'Común en refrigeración doméstica; presiones moderadas; revise pautas de retrofit y normativa.' },
  { slug: 'refrigerants-r410a', category: 'refrigerants', title: 'Refrigerant R-410A', summary: 'High-pressure blend used in many AC systems; requires POE oil and precise charging.', titleEs: 'Refrigerante R-410A', summaryEs: 'Mezcla de alta presión usada en muchos A/A; requiere aceite POE y carga precisa.' },
  { slug: 'refrigerants-r404a', category: 'refrigerants', title: 'Refrigerant R-404A', summary: 'Low/medium-temp commercial systems; glide considerations and environmental regulations apply.', titleEs: 'Refrigerante R-404A', summaryEs: 'Sistemas comerciales de baja/media temp.; considerar glide y regulaciones ambientales.' },
  { slug: 'refrigerants-r22', category: 'refrigerants', title: 'Refrigerant R-22', summary: 'Legacy HCFC—phase-out in many regions; alternatives and system considerations.', titleEs: 'Refrigerante R-22', summaryEs: 'HCFC legado en eliminación en muchas regiones; alternativas y consideraciones del sistema.' },
  { slug: 'sight-glass', category: 'components', title: 'Sight Glass Use', summary: 'Reading bubbles and moisture indicators; what they tell you about charge and contamination.', titleEs: 'Uso de mirilla', summaryEs: 'Lectura de burbujas e indicadores de humedad; qué indican sobre la carga y la contaminación.' },
  { slug: 'leak-detection', category: 'maintenance', title: 'Leak Detection Basics', summary: 'Electronic sniffers, UV dye, and soap solution—methods, safety, and verification.', titleEs: 'Búsqueda de fugas', summaryEs: 'Detectores electrónicos, tinte UV y solución jabonosa: métodos, seguridad y verificación.' },
  { slug: 'superheat-subcool', category: 'fundamentals', title: 'Superheat and Subcooling', summary: 'Measurement principles for correct charge and diagnosing flow restrictions.', titleEs: 'Sobrecalentamiento y subenfriamiento', summaryEs: 'Principios de medición para carga correcta y diagnóstico de restricciones de flujo.' },
  { slug: 'evap-condenser-coils', category: 'components', title: 'Evaporator and Condenser Coils', summary: 'Cleaning practices, fin care, and airflow effects on capacity and efficiency.', titleEs: 'Serpentines evaporador y condensador', summaryEs: 'Limpieza, cuidado de aletas y efectos del flujo de aire en capacidad y eficiencia.' },
  { slug: 'cap-tube', category: 'components', title: 'Capillary Tubes', summary: 'Simple metering devices in small systems; sensitivity to contamination and length/diameter changes.', titleEs: 'Tubos capilares', summaryEs: 'Dispositivos de expansión simples en sistemas pequeños; sensibles a contaminación y cambios de longitud/diámetro.' },
  { slug: 'defrost-methods', category: 'controls', title: 'Defrost Methods', summary: 'Time, temperature, and demand defrost—how each method works and when to use them.', titleEs: 'Métodos de deshielo', summaryEs: 'Deshielo por tiempo, temperatura y demanda: cómo funciona cada método y cuándo usarlo.' },
  { slug: 'safety-basics', category: 'safety', title: 'Safety Basics', summary: 'PPE, electrical lockout, cylinder handling, and ventilation to prevent accidents.', titleEs: 'Seguridad básica', summaryEs: 'EPP, bloqueo eléctrico, manejo de cilindros y ventilación para prevenir accidentes.' },
  { slug: 'charging-procedures', category: 'maintenance', title: 'Charging Procedures', summary: 'Weigh-in, superheat, or subcooling methods; record-keeping and leak checks are essential.', titleEs: 'Procedimientos de carga', summaryEs: 'Métodos por peso, sobrecalentamiento o subenfriamiento; registro y verificación de fugas son esenciales.' },
  { slug: 'vacuum-best-practices', category: 'maintenance', title: 'Vacuum Best Practices', summary: 'Deep vacuum, micron gauges, and proper hose setup for moisture removal before charging.', titleEs: 'Buenas prácticas de vacío', summaryEs: 'Vacío profundo, micrómetros y correcta conexión de mangueras para eliminar humedad antes de cargar.' },
  { slug: 'system-documentation', category: 'fundamentals', title: 'System Documentation', summary: 'Nameplates, wiring diagrams, and service logs—information that speeds up troubleshooting.', titleEs: 'Documentación del sistema', summaryEs: 'Placas, diagramas eléctricos y registros de servicio: información que acelera el diagnóstico.' },
]

